import React from "react";
import Head from "next/head";
import AdminHeader from "@/components/AdminHeader";

const AdminProfile = () => {
  return (
    <div>
      <Head>
        <title>KoonStore | Admin Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AdminHeader />
      <div className="h-[90vh] bg-[#F3F4F6]">
        <div className="h-[10vh] w-full bg-white flex justify-left items-center px-20 drop-shadow-md ">
          <h1 className="text-xl font-semibold"> Admin's Profile</h1>
        </div>
        <div className="md:py-16 md:px-20">
          <div className="bg-white rounded-lg p-5 drop-shadow-md">
            <div className="bg-white rounded-lg p-5 drop-shadow-md">
              <div className="md:flex justify-between md:px-16 lg:px-40">
                <div>
                  <h1 className="text-[#ED4A46] font-semibold py-5">
                    Update Profile
                  </h1>
                  <form action="" className="text-sm">
                    <div>
                      <label className="px-2">Name:</label> <br />
                      <input
                        className="border-2 border-[#F3F4F6]  w-60 rounded-md px-2 py-1"
                        type="text"
                        name=""
                        aria-label="/"
                        placeholder="Enter product name"
                      />
                    </div>
                    <br />
                    <div>
                      <label className="px-2">Price:</label> <br />
                      <input
                        className="border-2 border-[#F3F4F6] w-60 rounded-md px-2 py-1"
                        type="text"
                        name=""
                        aria-label="/"
                        placeholder="Enter product price"
                      />
                    </div>
                    <br />
                    <div>
                      <label className="px-2">Category:</label> <br />
                      <input
                        className="border-2 border-[#F3F4F6] w-60 rounded-md px-2 py-1"
                        type="text"
                        name=""
                        aria-label="/"
                        placeholder="Enter product category"
                      />
                    </div>
                    <br />
                    <br />
                    <button className="px-5 py-2 bg-[#ED4A46] rounded-lg text-[#F3F4F6] hover:text-[#ED4A46] hover:bg-[#F3F4F6] border-2 border-[#ED4A46] ease-in duration-300">
                      Update Profile
                    </button>
                  </form>
                </div>
                <br className="md:hidden" />
                <hr className="md:hidden" />
                <div>
                  <h1 className="text-[#ED4A46] font-semibold py-5">
                    Create User
                  </h1>
                  <form action="" className="text-sm">
                    <div>
                      <label className="px-2">Firstname:</label> <br />
                      <input
                        className="border-2 border-[#F3F4F6] w-60 rounded-md px-2 py-1"
                        type="text"
                        name=""
                        aria-label="/"
                        placeholder="Enter firstname"
                      />
                    </div>
                    <br />
                    <div>
                      <label className="px-2">Lastname:</label> <br />
                      <input
                        className="border-2 border-[#F3F4F6] w-60 rounded-md px-2 py-1"
                        type="text"
                        name=""
                        aria-label="/"
                        placeholder="Enter lastname"
                      />
                    </div>
                    <br />
                    <div>
                      <label className="px-2">Username:</label> <br />
                      <input
                        className="border-2 border-[#F3F4F6] w-60 rounded-md px-2 py-1"
                        type="text"
                        name=""
                        aria-label="/"
                        placeholder="Enter username"
                      />
                    </div>
                    <br />
                    <div className="md:flex gap-5">
                      <div>
                        <label className="px-2">Password:</label> <br />
                        <input
                          className="border-2 border-[#F3F4F6]  rounded-md px-2 py-1"
                          type="text"
                          name=""
                          aria-label="/"
                          placeholder="Enter password"
                        />
                      </div>
                      <br className="md:hidden" />
                      <div>
                        <label className="px-2">Confirm Password:</label> <br />
                        <input
                          className="border-2 border-[#F3F4F6]  rounded-md px-2 py-1"
                          type="text"
                          name=""
                          aria-label="/"
                          placeholder="Confirm password"
                        />
                      </div>
                    </div>

                    <br />
                    <div className="md:flex gap-5 items-end">
                      <div>
                        <label className="px-2">Role:</label> <br />
                        <input
                          className="border-2 border-[#F3F4F6] w-60 rounded-md px-2 py-1"
                          type="text"
                          name=""
                          aria-label="/"
                          placeholder="Enter role - (admin or client)"
                        />
                      </div>
                      <br />
                      <br />
                      <div>
                        <button className="px-5 py-2 bg-[#ED4A46] rounded-lg text-[#F3F4F6] hover:text-[#ED4A46] hover:bg-[#F3F4F6] border-2 border-[#ED4A46] ease-in duration-300">
                          Create User
                        </button>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AdminProfile;
