import React from "react";
import Head from "next/head";
import AdminHeader from "@/components/AdminHeader";
import Orders from "@/components/orders/Orders";

const AdminOrder = () => {
  return (
    <div>
      {" "}
      <Head>
        <title>KoonStore</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AdminHeader />
      <div className="h-[90vh] bg-[#F3F4F6]">
        <div className="h-[10vh] w-full bg-white flex justify-left items-center px-20 drop-shadow-md">
          <h1 className="text-xl font-semibold">Orders</h1>
        </div>
        <div className="p-20">
          <div className="bg-white rounded-lg p-5 drop-shadow-md">
            <div className="bg-white rounded-lg p-5 drop-shadow-md">
              <Orders />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AdminOrder;
