import React, { FormEvent, SyntheticEvent, useState } from "react";
import Head from "next/head";
import AdminHeader from "@/components/AdminHeader";
import Product from "@/types/products";
import axios from "axios";
import { store } from "../redux/authStore";

const AdminCreateProduct = () => {
  const [state, setState] = useState<Product>({} as Product);

  function onChange(e: FormEvent<HTMLInputElement>) {
    setState({
      ...state,
      [e.currentTarget.name]: e.currentTarget.value,
    });
  }

  const newProduct = async (e: SyntheticEvent) => {
    e.preventDefault();
    try {
      const headers = {
        "Content-Type": "application/json",
        Authorization: `Bearer ${store.getState().token}`,
      };

      const response = await axios.post(
        "http://localhost:3000/admin/products/create",
        state, {headers}
      );
      console.log(response.data);
    } catch (err) {
      alert(err);
    }
  };
  return (
    <div>
      <Head>
        <title>KoonStore | Create Product</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AdminHeader />
      <div className="h-[90vh] bg-[#F3F4F6]">
        <div className="h-[10vh] w-full bg-white flex justify-left items-center px-20 drop-shadow-md ">
          <h1 className="text-xl font-semibold">Create Product</h1>
        </div>
        <div className="p-5 lg:p-20">
          <div className="bg-white rounded-lg p-5 drop-shadow-md">
            <div className="bg-white rounded-lg p-5 lg:py-5 lg:px-20 drop-shadow-md">
              <h1 className="text-[#ED4A46] font-semibold py-5">
                Create Product
              </h1>
              <form onSubmit={newProduct} className="text-sm">
                <div>
                  <label className="px-2">Name:</label> <br />
                  <input
                    className="border-2 border-[#F3F4F6] w-60 rounded-md px-2 py-1"
                    type="text"
                    name="name"
                    onChange={onChange}
                    aria-label="/"
                    placeholder="Enter product name"
                  />
                </div>
                <br />
                <div>
                  <label className="px-2">Price:</label> <br />
                  <input
                    className="border-2 border-[#F3F4F6] w-60 rounded-md px-2 py-1"
                    type="number"
                    name="price"
                    onChange={onChange}
                    aria-label="/"
                    placeholder="Enter product price"
                  />
                </div>
                <br />
                <div>
                  <label className="px-2">Category:</label> <br />
                  <input
                    className="border-2 border-[#F3F4F6] w-60 rounded-md px-2 py-1"
                    type="text"
                    name="category"
                    onChange={onChange}
                    aria-label="/"
                    placeholder="Enter product category"
                  />
                </div>
                <br />
                <br />
                <button
                  type="submit"
                  className="px-5 py-2 bg-[#ED4A46] rounded-lg text-[#F3F4F6] hover:text-[#ED4A46] hover:bg-[#F3F4F6] border-2 border-[#ED4A46] ease-in duration-300"
                >
                  Add product
                </button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AdminCreateProduct;
