import React from "react";
import Head from "next/head";
import AdminHeader from "@/components/AdminHeader";
import Products from "@/components/products/Products";
import Link from "next/link";

const AdminAllProducts = () => {
  return (
    <div>
      <Head>
        <title>KoonStore | All Products</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AdminHeader />
      <div className="h-[90vh] bg-[#F3F4F6]">
        <div className="h-[10vh] w-full bg-white flex justify-left items-center px-20 drop-shadow-md">
          <h1 className="text-xl font-semibold">All Products</h1>
        </div>
        <div className="p-20">
          <div className="bg-white rounded-lg p-5 drop-shadow-md">
            <div className="flex mb-5">
              <Link href="/admincreateproduct">
                <h2 className="px-5 py-2 bg-[#ED4A46] rounded-lg text-[#F3F4F6] hover:text-[#ED4A46] hover:bg-[#F3F4F6] border-2 border-[#ED4A46] ease-in duration-300">
                  + Add Product
                </h2>
              </Link>
            </div>

            <div className="bg-white rounded-lg p-5 drop-shadow-md">
              <Products />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AdminAllProducts;
