import React from "react";
import Head from "next/head";
import AdminHeader from "@/components/AdminHeader";

const AdminCreateProduct = () => {
  return (
    <div>
      <Head>
        <title>KoonStore</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AdminHeader />
      <div className="h-[90vh] bg-[#F3F4F6]">
        <div className="h-[10vh] w-full bg-white flex justify-left items-center px-20 drop-shadow-md">
          <h1 className="text-xl font-semibold">Create Product</h1>
        </div>
        <div className="p-20">
          <div className="bg-white rounded-lg p-5 drop-shadow-md">
            <div className="bg-white rounded-lg p-5 drop-shadow-md">
              <h1 className="text-[#ED4A46] font-semibold py-5">
                Create Product
              </h1>
              <form action="" className="text-sm">
                <div>
                  <label>Name:</label> <br />
                  <input
                    type="text"
                    name=""
                    aria-label="/"
                    placeholder="Enter product name"
                  />
                </div>
                <br />
                <div>
                  <label>Price:</label> <br />
                  <input
                    type="text"
                    name=""
                    aria-label="/"
                    placeholder="Enter product price"
                  />
                </div>
                <br />
                <div>
                  <label>Category:</label> <br />
                  <input
                    type="text"
                    name=""
                    aria-label="/"
                    placeholder="Enter product category"
                  />
                </div>
                <br />
                <br />
                <button className="px-5 py-2 bg-[#ED4A46] rounded-lg text-[#F3F4F6] hover:text-[#ED4A46] hover:bg-[#F3F4F6] border-2 border-[#ED4A46] ease-in duration-300">
                  Add product
                </button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AdminCreateProduct;
