import AdminHeader from "@/components/AdminHeader";
import React from "react";
import Head from "next/head";
import ClientHeader from "@/components/ClientHeader";

const Clientproducts = () => {
  return (
    <div>
      <Head>
        <title>KoonStore | Client Name</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ClientHeader />
    </div>
  );
};

export default Clientproducts;
