import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import cart from "../public/images/cart.png";
import Header from "@/components/Header";
import { store, setToken } from "../redux/authStore";

export default function Home() {
  // const dispatch = () => {
  //   store.dispatch(setToken("KuunStore"));
  // };

  return (
    <>
      <Head>
        <title>KoonStore</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className=" h-[92vh] md:h-[72vh] w-full bg-gradient-to-r from-[#ED8B5F] via-[#F0A07D] to-[#ED8B5F] flex justify-center items-center">
        <div className="md:flex">
          <div className="md:w-1/2 flex justify-center items-center">
            <div className="max-w-[900px]">
              <h1 className="text-3xl text-center md:text-left md:text-5xl md:pl-10 lg:text-6xl font-bold text-white">
                Welcome to
              </h1>
              <h2 className="text-5xl text-center md:text-left md:text-7xl md:pl-10 lg:text-8xl font-extrabold">
                KoonStore<span className="text-[#ED4A46]">!</span>
              </h2>
              <br className="hidden md:block" />
              <p className="hidden md:block md:pl-10 text-center md:text-left text-sm text-[#F8CCB9]">
                Discover endless treasures, just a click away.
              </p>
              <p className="md:pl-10 text-center md:text-left max-w-[400px] md:max-w-none text-sm text-[#F8CCB9]">
                Top quality products designed to meet customer requirements and
                bring satisfaction.
              </p>
              <br className="hidden md:block" />
              <div className="flex">
                <Link href="/login" className="hidden md:block md:pl-10 ">
                  <p className="text-white text-md font-thin px-8 py-2 bg-[#ED4A46] rounded-md">
                    Shop Now
                  </p>
                </Link>
              </div>
            </div>
          </div>
          <div className="flex justify-center md:w-1/2 max-w-[800px] ">
            <Image src={cart} alt="cart" className="w-4/6 md:w-[90%] "></Image>
          </div>
          <br className="block md:hidden" />
          <div className="flex justify-center">
            <Link href="/login" className=" md:hidden md:pl-10">
              <p className="text-white text-md font-thin px-8 py-2 bg-[#ED4A46]  rounded-md">
                Shop Now
              </p>
            </Link>
          </div>
        </div>
      </div>
      <div className="hidden md:flex items-center h-[20vh] w-full">
        <div className="w-full">
          <div className="flex justify-around ">
            <div className="text-center">
              <h1 className="text-5xl pb-2 font-bold">1.1k</h1>
              <p className="text-sm">Registered Shoppers</p>
            </div>
            <div className="text-center ">
              <h1 className="text-5xl pb-2 font-bold">2k+</h1>
              <p className="text-sm">Available products </p>
            </div>
            <div className="text-center">
              <h1 className="text-5xl pb-2 font-bold">100%</h1>
              <p className="text-sm">Positive Reviews</p>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
